### ISSUE TITLE
custom widgets and React.memo

### ISSUE THREAD

**Issue by revolunet** [rjsf-team/react-jsonschema-form#1309]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Looks like the widgets props doesnt like react.memo Components for some reason.

### Steps to Reproduce

Once wrapped in `React.memo` the component is not usable anymore as a form widget. this also impacts react-redux `connect` wrapper with produces a `React.memo` :)

Here's a repro : https://codesandbox.io/s/reactredux-connect-with-reactjsonschemaform-issue-8023j
 
#### Expected behavior

React memoified components should work :)

#### Actual behavior

Throws with `Unsupported widget definition: object`

### Version

1.6.0

**Comment by epicfaace** [comment]
I believe the fix would involve adding `ReactIs.isMemo(widget)` here: https://github.com/mozilla-services/react-jsonschema-form/blob/41fce4aad12177757eaec823277587aa81166ad2/src/utils.js#L106

**Comment by coder-guy22296** [comment]
Is anybody currently working on a solution for this issue?

**Comment by epicfaace** [comment]
No, not as of now -- @coder-guy22296 would you be able to fix it?

**Comment by Alexandre27** [comment]
Can confirm that adding `ReactIs.isMemo(widget)` solves the problem.
I was making a PR to this issue but noticed that custom fields also have a problem with memo components, it's just a warning from propTypes, so its more annoying than anything else.
For a custom field I have lots of warnings:
```
Invalid prop 'fields.customField' of type 'object' supplied to 'Form', expected 'function'

Invalid prop 'registry.fields.customField' of type 'object' supplied to 'SchemaField', expected 'function'.

Invalid prop 'registry.fields.customField' of type 'object' supplied to 'ObjectField', expected 'function'.

Invalid prop 'registry.fields.customField' of type 'object' supplied to 'StringField', expected 'function'.

Invalid prop 'registry.fields.customField' of type 'object' supplied to 'NumberField', expected 'function'.

Invalid prop 'registry.fields.customField' of type 'object' supplied to 'ArrayField', expected 'function'.
```

I tried adding this to Form.js

```
    fields: PropTypes.objectOf(
      PropTypes.oneOfType([PropTypes.func, PropTypes.object])
    ),
    ArrayFieldTemplate: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
    ObjectFieldTemplate: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
    FieldTemplate: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
```

and this to types.js

```
  ArrayFieldTemplate: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
  FieldTemplate: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
  ObjectFieldTemplate: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
  definitions: PropTypes.object.isRequired,
  fields: PropTypes.objectOf(
    PropTypes.oneOfType([PropTypes.func, PropTypes.object])
  )
```
and it did silence those warnings but a new one appears `React.createElement: type is invalid -- expected a string (for built-in components) or a class/function
 (for composite components) but got: object.` on MergedWidget.
 
@epicfaace I'm not very familiar with the entire codebase, any advice on how to fix this one?

**Comment by RobCubed** [comment]
Simple workaround for now if you're using redux connected components -

At the bottom of your custom widget component change:

`export default connect(mapStateToProps)(ContractCategorySuperSelect)`

to:

```
var ReduxWrapped = connect(mapStateToProps)(ContractCategorySuperSelect)

class CategorySelectWrapper extends Component {
  render () {
    return (
      <ReduxWrapped {...this.props} />
    )
  }
}

export default CategorySelectWrapper
```

Essentially just returning a standard react component with the redux connected component inside it.

**Comment by Alexandre27** [comment]
@epicfaace sorry for the delay, I was on vacations. Created a draft PR with the elementType change but I am getting the same errors. If needed I can create a playground showcasing the error.

**Comment by epicfaace** [comment]
Fixed by #1447.

**Comment by travisdahl** [comment]
Still experiencing the same issue with the alpha. Had to use @RobCubed 's solution to work around it

**Comment by jansenchan** [comment]
Still experiencing the same issue with the v2.0.0.

The test is failure https://github.com/rjsf-team/react-jsonschema-form/blob/v2.0.0/packages/core/test/utils_test.js#L3596 .

Here is the pointer https://github.com/rjsf-team/react-jsonschema-form/blob/v2.0.0/packages/core/src/utils.js#L114 .

ReactIs.isMemo just judge the React element instance not the React Component. 
https://github.com/facebook/react/blob/master/packages/react-is/src/ReactIs.js#L31

**Comment by epicfaace** [comment]
@jansenchan I'm a bit confused... the test passes on CI, are you saying the test fails if you run with a specific React version (v16.9.0)?

**Comment by jansenchan** [comment]
> @jansenchan I'm a bit confused... the test passes on CI, are you saying the test fails if you run with a specific React version (v16.9.0)?

``` javascript
import React from 'react';
import ReactIs from 'react-is';

const C = props => <div {...props} />
const MC = React.memo(C);

// while ReactIs's version is `16.12.0~latest(16.13.1 for now)`
console.log(ReactIs.isMemo(MC)); // false
console.log(ReactIs.isMemo(<MC />)); // true
```

For the dependencies: `"react-is": "^16.9.0"`, it will resolve `react-is@16.13.1`, when I install the latest react-jsonschema-form.

You can reinstall the dependencies without `package-lock.json` and run the test again. [The test](https://github.com/rjsf-team/react-jsonschema-form/blob/v2.0.0/packages/core/test/utils_test.js#L3596) will fail (while react-is >=16.12.0) .

**Comment by knilink** [comment]
just checked the file in the `react-jsonschema-form/lib/typs.js`  at 1.8.1. that line 17 was still  `FieldTemplate: _propTypes["default"].func,` 
so probably something wrong with the build or while packing the package?
