### ISSUE TITLE
@rjsf/antd is too big

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1875]
### Description

[@rjsf/antd](https://www.npmjs.com/package/@rjsf/antd) is too big -- it's around 6.7 MB. Need to analyze why it's so big and then reduce the size.

### Version

2.2.0

**Comment by LouizFC** [comment]
isnt it fixed by #1900 ? probably can be closed

**Comment by epicfaace** [comment]
That's correct, thanks!

**Comment by rmannibucau** [comment]
Hi,

Seems antd still does not have a production.min nor "light" bundle - current bundle is around 1.1M - compared to material-ui or bootstrap-4 dist/. Is it intended? Any hope it gets enhanced?

Thanks.
