### ISSUE TITLE
Errors with version 4.0 and material-ui 4

### ISSUE THREAD

**Issue by leonbloy** [rjsf-team/react-jsonschema-form#2721]
Installing version 4.0 @rjsf/core and @rjsf/material-ui, alongside with my material-ui 4, I get the warning

`npm WARN @rjsf/material-ui@4.0.0 requires a peer of @rjsf/core@^3.0.0 but none is installed. You must install peer dependencies yourself.`

(and indeed, in the package.json of @rjsf/material-ui one finds "@rjsf/core@^3.0.0" , that seems wrong)

Furthermore, if I ignore the install warning , npm start gives compile warnings

```
./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@mui/icons-material' in 'C:\wk\pcnt\trake\trake-ui\node_modules\@rjsf\material-ui\dist'

./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@mui/material' in 'C:\wk\pcnt\trake\trake-ui\node_modules\@rjsf\material-ui\dist'   
```

... and when runnning I get on console

```
Error: Cannot find module '@mui/material'
    at webpackMissingModule (material-ui.esm.js:1256:1)
    at Module../node_modules/@rjsf/material-ui/dist/material-ui.esm.js (material-ui.esm.js:1256:1)
```

Using react 17 and Node 14 with

@material-ui/core: 4.12.3
@material-ui/system: 4.12.1
@material-ui/icons 4.11.2
@rjsf/core: 4.0.0
@rjsf/material-ui: 4.0.0

**Comment by leonbloy** [comment]
In the above scenario, in spite of the warnings/errors, the form displays.

But it breaks when I set `tagName="div"
```

`import Form from '@rjsf/material-ui';
...
const schema = {
  title: 'Test form', 
  type: 'object',  
  properties: {    name: {      type: 'string',    },    age: {      type: 'number',    },  },
};
...
<Form schema={schema} tagName="div" />
```

throws  
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

```
Check the render method of `FieldTemplate`.
    at createFiberFromTypeAndProps (react-dom.development.js:24851:1)
    at createFiberFromElement (react-dom.development.js:24876:1)
    ....
index.js:1451 The above error occurred in the <WrapIfAdditional> component:
    at WrapIfAdditional (https://localhost:3000/static/js/30.chunk.js:8865:23)
    at FieldTemplate (https://localhost:3000/static/js/30.chunk.js:8935:17)
    at SchemaField (https://localhost:3000/static/js/30.chunk.js:3909:5)

```

This does not happen if I import the Form from '@rjsf/core'

**Comment by heath-freenome** [comment]
@epicfaace it seems like the major version upgrade probably needs to automatically bump the peer-dependencies for core... I'm working on a PR to fix a few of these issues right now

**Comment by leonbloy** [comment]
No problems in my setup if I revert both @rjsf/core and @rjsf/material-ui to previous versions (3.2.1)

**Comment by epicfaace** [comment]
Thanks Heath! We may also want to add a section in the releasing
documentation that reminds one to manually bump the peer dependencies upon
a major version release.

Ashwin Ramaswami

**Comment by heath-freenome** [comment]
@leonbloy Given how the new material-ui is built, using the `tagName` will entirely break it. Is there a reason why you need the `tagName` to be `div`?

**Comment by leonbloy** [comment]
@heath-freenome  I definetely need `tagName="div"` because I need to place the fields inside an existing form

**Comment by heath-freenome** [comment]
> @heath-freenome I definetely need `tagName="div"` because I need to place the fields inside an existing form

Got it... My fix will support your use case as well.

**Comment by heath-freenome** [comment]
@epicfaace In my own build I am also seeing these which I believe my fix eliminates as well:
```
      ModuleNotFoundError: Cannot find module '@mui/material' from 'node_modules/@rjsf/material-ui/dist/material-ui.cjs.development.js'
          at Resolver.resolveModule (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-resolve/build/resolver.js:324:11)
          at Resolver._getVirtualMockPath (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-resolve/build/resolver.js:471:14)
          at Resolver._getAbsolutePath (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-resolve/build/resolver.js:457:14)
          at Resolver.getModuleID (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-resolve/build/resolver.js:424:31)
          at Runtime._shouldMock (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-runtime/build/index.js:1917:37)
          at Runtime.require [as requireModuleOrMock] (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-runtime/build/index.js:1204:14)
          at Object.<anonymous> (/home/travis/build/freenome/freenome-core-ui/node_modules/@rjsf/material-ui/src/Theme5/Mui5Context.tsx:10:9)
          at Runtime._execModule (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-runtime/build/index.js:1646:24)
          at Runtime._loadModule (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-runtime/build/index.js:1185:12)
          at Runtime.requireModule (/home/travis/build/freenome/freenome-core-ui/node_modules/jest-runtime/build/index.js:1009:12) {
        code: 'MODULE_NOT_FOUND',
        hint: '',
        requireStack: undefined,
        siblingWithSimilarExtensionFound: false,
        moduleName: '@mui/material',
        _originalMessage: "Cannot find module '@mui/material' from 'node_modules/@rjsf/material-ui/dist/material-ui.cjs.development.js'"
      }
      at Object.<anonymous> (node_modules/@rjsf/material-ui/src/Theme5/Mui5Context.tsx:13:11)
```

**Comment by OliverDudgeon** [comment]
I'm still getting `Module not found: Can't resolve '@material-ui/core'` warnings when using 4.0.1. 

```ts
import { withTheme } from '@rjsf/core';
import { Theme5 as Mui5Theme } from '@rjsf/material-ui';

export const Form = withTheme(Mui5Theme);
```

**Comment by ryedin** [comment]
Seeing same issue as above. We can get past all of the warnings by also installing `@material-ui/core` and `@material-ui/icons`, however, as can be guessed, this makes the bundle size **_hash_tag_ridiculous_** (dev bundle goes from 1.1MB for just core to 7.6MB for the material theme)

Clearly there are some dep fixes that were missed. 

Also just in general wondering why this bundle is so big to begin with (are there possible better tree-shaking optimizations that could be made with the exports, or is this purely the ajv problem?)

**Comment by heath-freenome** [comment]
> I'm still getting Module not found: Can't resolve '@material-ui/core' warnings when using 4.0.1.

Will work on this soon

**Comment by joriswitteman** [comment]
This is still kaput. https://github.com/rjsf-team/react-jsonschema-form/issues/2762

**Comment by heath-freenome** [comment]
> This is still kaput. #2762

Which part? The errors were resolved in `v4.1.0` the module size fix will be coming in `v4.1.1`

**Comment by joriswitteman** [comment]
I and the users in #2762 are still having the same errors with `v4.1.0` as are being posted in that issue.

**Comment by jukkahuuskonen** [comment]
This seems to get worse with v4.1.1. with v4.1.0 I am getting these 2 errors:
![image](https://user-images.githubusercontent.com/42405685/160594412-e897e8c3-f49b-4126-8a83-a19908dc287c.png)

And my co-worker has th v4.1.1 with these errors:
![image](https://user-images.githubusercontent.com/42405685/160594588-b0c0b569-d0b2-4dd9-bde8-005d6f057d20.png)

**Comment by heath-freenome** [comment]
This is a known issue with the way Mui 4 and 5 support were built to be side-by-side. There are webpack tricks that can be used to eliminate the warnings.

# Webpack 5

Add the following in your `webpack.config.js` to eliminate the errors for Material-UI v5 when you are only using v4:
```
// Have webpack 5 set the fallbacks for the resolver for Mui 5 to be false
config.resolve.fallback = { '@mui/material': false, '@mui/icons-material': false };
```

Add the following in your `webpack.config.js` to eliminate the errors for Material-UI v4 when you are only using v5:
```
// Have webpack 5 set the fallbacks for the resolver for Mui 4 to be false
config.resolve.fallback = { '@material-ui/core': false, '@material-ui/icons': false };
```

# Webpack 4

Add the following in your `webpack.config.js` to eliminate the errors for Material-UI v5 when you are only using v4:
```
// Alias Material-ui 5 to be Material-ui 4
config.resolve.alias['@mui/material'] = require.resolve('@material-ui/core');
config.resolve.alias['@mui/icons-material'] = require.resolve('@material-ui/icons');
```

Add the following in your `webpack.config.js` to eliminate the errors for Material-UI v4 when you are only using v5:
```
// Alias Material-ui 4 to be Material-ui 5
config.resolve.alias['@material-ui/core'] = require.resolve('@mui/material');
config.resolve.alias['@material-ui/icons'] = require.resolve('@mui/icons-material');
```

**Comment by jukkahuuskonen** [comment]
> This is a known issue with the way Mui 4 and 5 support were built to be side-by-side. There are webpack tricks that can be used to eliminate the warnings.
> ...

Yes, and like in #2762 was mentioned, that is hard to do with CRA.

Does this mean that there is not going to be a fix for this in near future?

How about you separate the Mui4 and Mui5 into separate packages and possible mark v4 as legacy version?
