### ISSUE TITLE
Issue using oneof

### ISSUE THREAD

**Issue by harrydoddnoble** [rjsf-team/react-jsonschema-form#4050]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

I am using the following JSON with oneof:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "activityChoice": {
      "type": "string",
      "title": "Do you want to ski or swim?",
      "enum": [
        "ski",
        "swim"
      ],
      "piqRef": "Question 1"
    }
  },
  "required": [
    "activityChoice"
  ],
  "oneOf": [
    {
      "properties": {
        "activityChoice": {
          "const": "swim"
        },
        "swimTrunksColor": {
          "type": "string",
          "title": "What colour swimming trunks do you want?",
          "piqRef": "Question 2"
        }
      },
      "required": [
        "swimTrunksColor"
      ]
    },
    {
      "properties": {
        "activityChoice": {
          "const": "ski"
        },
        "skiLength": {
          "type": "number",
          "title": "What length skis do you want?",
          "piqRef": "Question 3"
        }
      },
      "required": [
        "skiLength"
      ]
    }
  ]
}
```

While the logic works on the playground but it also shows the drop down saying Option 1 and Option 2, and it also has an extra text box called activityChoice -
<img width="685" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/114193994/b976726b-e9f9-48a5-932c-a54cd4ac5d3f">

### Expected Behavior

 it should really just show the second text box question (the ski size or swimming trunks colour) depending on which option you select. Anyone able to advise on why this would happen? I can create a if-then-else but I already have a full schema so this isn't really an option.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by nickgros** [comment]
@harrydoddnoble RJSF has no way of knowing that you discriminator on each `oneOf` field using that constant value. One change you could make is to give each of your `oneOf` schemas a title, and then use the UI Schema to hide the field that you don't want to show.

[Here's a playground example.](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzd2ltVHJ1bmtzQ29sb3IiOiJmIiwiYWN0aXZpdHlDaG9pY2UiOiJmIn0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYWN0aXZpdHlDaG9pY2UiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRG8geW91IHdhbnQgdG8gc2tpIG9yIHN3aW0/IiwiZW51bSI6WyJza2kiLCJzd2ltIl0sInBpcVJlZiI6IlF1ZXN0aW9uIDEifX0sInJlcXVpcmVkIjpbImFjdGl2aXR5Q2hvaWNlIl0sIm9uZU9mIjpbeyJ0aXRsZSI6InN3aW0iLCJwcm9wZXJ0aWVzIjp7ImFjdGl2aXR5Q2hvaWNlIjp7ImNvbnN0Ijoic3dpbSJ9LCJzd2ltVHJ1bmtzQ29sb3IiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiV2hhdCBjb2xvdXIgc3dpbW1pbmcgdHJ1bmtzIGRvIHlvdSB3YW50PyIsInBpcVJlZiI6IlF1ZXN0aW9uIDIifX0sInJlcXVpcmVkIjpbInN3aW1UcnVua3NDb2xvciJdfSx7InRpdGxlIjoic2tpIiwicHJvcGVydGllcyI6eyJhY3Rpdml0eUNob2ljZSI6eyJjb25zdCI6InNraSJ9LCJza2lMZW5ndGgiOnsidHlwZSI6Im51bWJlciIsInRpdGxlIjoiV2hhdCBsZW5ndGggc2tpcyBkbyB5b3Ugd2FudD8iLCJwaXFSZWYiOiJRdWVzdGlvbiAzIn19LCJyZXF1aXJlZCI6WyJza2lMZW5ndGgiXX1dfSwidWlTY2hlbWEiOnsiYWN0aXZpdHlDaG9pY2UiOnsidWk6d2lkZ2V0IjoiaGlkZGVuIn19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnt9fQ==)

**Comment by harrydoddnoble** [comment]
Amazing. Will check this out - thank you!

**Comment by harrydoddnoble** [comment]
Aah I'm still struggling a bit with this one - with the given solution you lose the title of the ski/swim question. I'm also working with an existing JSON schema and I'm not sure I understand how to get this to work properly.. any help/ideas would be very welcome!

In the example below you are asked if you insure the property, if you select yes it should show the rest of the questions (which in turn have some nestled logic) but if you select no it should show nothing..

```
{
  "properties": {
    "isInsured": {
      "piqRef": "A8.2",
      "title": "Do you insure the property?",
      "enum": [
        "Yes",
        "No"
      ],
      "type": "string"
    }
  },
  "oneOf": [
    {
      "properties": {
        "difficultiesObtainingInsurance": {
          "piqRef": "A8.1",
          "title": "Have you had any difficulty obtaining competitively priced building insurance due to the structure or location of the property or had insurance refused?",
          "type": "object",
          "properties": {
            "abnormalRiseInPremiums": {
              "piqRef": "A8.1a",
              "title": "Subject to abnormal rise in premiums?",
              "discriminator": {
                "propertyName": "yesNo"
              },
              "type": "object",
              "oneOf": [
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "No"
                      ]
                    }
                  }
                },
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "Yes"
                      ]
                    },
                    "details": {
                      "piqRef": "A8.1a1.1",
                      "title": "Provide details",
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              ],
              "properties": {
                "yesNo": {
                  "piqRef": "A8.1a1",
                  "enum": [
                    "Yes",
                    "No"
                  ],
                  "type": "string"
                }
              }
            },
            "subjectToHighExcesses": {
              "piqRef": "A8.1b",
              "title": "Subject to high excesses?",
              "discriminator": {
                "propertyName": "yesNo"
              },
              "type": "object",
              "oneOf": [
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "No"
                      ]
                    }
                  }
                },
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "Yes"
                      ]
                    },
                    "details": {
                      "piqRef": "A8.1b2",
                      "title": "Provide details",
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              ],
              "properties": {
                "yesNo": {
                  "piqRef": "A8.1b1",
                  "enum": [
                    "Yes",
                    "No"
                  ],
                  "type": "string"
                }
              }
            },
            "subjectToUnusualConditions": {
              "piqRef": "A8.1c",
              "title": "Subject to unusual conditions?",
              "discriminator": {
                "propertyName": "yesNo"
              },
              "type": "object",
              "oneOf": [
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "No"
                      ]
                    }
                  }
                },
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "Yes"
                      ]
                    },
                    "details": {
                      "piqRef": "A8.1c2",
                      "title": "Provide details",
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              ],
              "properties": {
                "yesNo": {
                  "piqRef": "A8.1c1",
                  "enum": [
                    "Yes",
                    "No"
                  ],
                  "type": "string"
                }
              }
            },
            "refused": {
              "piqRef": "A8.1d",
              "title": "Refused?",
              "discriminator": {
                "propertyName": "yesNo"
              },
              "type": "object",
              "oneOf": [
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "No"
                      ]
                    }
                  }
                },
                {
                  "properties": {
                    "yesNo": {
                      "enum": [
                        "Yes"
                      ]
                    },
                    "details": {
                      "piqRef": "A8.1d2",
                      "title": "Provide details",
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              ],
              "properties": {
                "yesNo": {
                  "piqRef": "A8.1d1",
                  "enum": [
                    "Yes",
                    "No"
                  ],
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  ]
}
```

**Comment by nickgros** [comment]
You might be able to accomplish what you want with the uiSchema when we release a new version of RJSF that includes #4055

I spent a few minutes looking at your schema and was a bit overwhelmed. What you are trying to do is really best served by conditional logic in schemas. You said you can't use if/then/else, but could you use [dependencies](https://rjsf-team.github.io/react-jsonschema-form/docs/json-schema/dependencies#schema-dependencies)? This is another tool that you can use to implement conditional logic in your JSON Schema.

**Comment by harrydoddnoble** [comment]
It's an open source schema
<https://github.com/Property-Data-Trust-Framework/schemas/blob/master/src/schemas/v2/combined.json>
that we use so it's tricky to make too many changes - we could look at
creating a script to run some transformations but obviously there is then a
risk that as things change on the main schema things break our end! From a
logic point of view everything currently works, eg. it shows the relevant
fields when Yes/No is selected but it also shows duplications of the
questions.

**Comment by codisfy** [comment]
> You might be able to accomplish what you want with the uiSchema when we release a new version of RJSF that includes https://github.com/rjsf-team/react-jsonschema-form/pull/4055

@nickgros Do you know when will the next release be? I pulled a lot of hair today finally to realize that anyOf/oneOf on UISchema needed some updates and hasn't made to the release.

**Comment by nickgros** [comment]
@codisfy We released 5.17.0 yesterday, so you should be able to try out the new uiSchema functionality now

**Comment by nickgros** [comment]
@harrydoddnoble now that #4055 was added to 5.17.0, are you able to use the uiSchema to achieve your desired behavior?

**Comment by harrydoddnoble** [comment]
We are just updating the schema and then will try. It does appear to work
with the logic but I'm still not quite sure how to hide the duplicated
fields.
